[package]
name = "haasteikko-backend"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = { workspace = true }
rusqlite = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
reqwest = { version = "0.13.2", features = ["json"] }
chrono = "0.4.43"
uuid = { version = "1.20.0", features = ["v4", "serde"] }
tower-http = { version = "0.6.8", features = ["cors"] }

[dev-dependencies]
tempfile = "3.25.0"
